### ISSUE TITLE
`null` interpolation

### ISSUE THREAD

**Issue by berdario** [mustache/spec#101]
Which alternative should be part of the spec?

```
  - data: {nullkey: null }
    template: "{{nullkey}}"
    expected: ""
```

```
  - data: {nullkey: null }
    template: "{{nullkey}}"
    expected: "null"
```

I've seen a Mustache implementation that yields the latter, but then I checked [the demo](https://mustache.github.io/#demo), and its behavior instead was the former

**Comment by groue** [comment]
What do you think?

**Comment by berdario** [comment]
Me?

I think that the former behavior might be less surprising, but I don't have a strong opinion.

I don't think that this should be left unspecified

**Comment by groue** [comment]
This repository has not been updated in years.

**Comment by berdario** [comment]
Yes, about 1year and a half, but since the Ruby implementation repository is still being worked on, and that whoever has write rights on that repo should also have them on this one, there's no excuse for this situation to persist (I know that you're not part of the organization, so I'm not blaming you)

~~Either they pick up the burden, or they give access to others to this repo and the [website](https://github.com/mustache/mustache.github.com) repo or, as a third alternative, if they don't want to maintain the spec anymore they should declare it an unmaintained/deprecated, give up any pretense of being a complete spec and let other standards flourish~~

Ok, I strikethrough'ed the text since I'm afraid it could've come off as a bit bitter... also I found this old blog post: http://writing.jan.io/mustache-2.0.html So the idea of a Mustache2 is not new, and Handlebars apparently never went anywhere (outside of javascript and few languages)

I guess that I should get used to the idea that good and complete standards are an exception, not the rule

**Comment by groue** [comment]
Yes, this is very frustrating. You may be interested in https://github.com/groue/GRMustacheSpec, an extended Mustache test suite (which addresses the [rendering of null](https://github.com/groue/GRMustacheSpec/blob/master/Tests/general/variables.json#L65))

**Comment by Danappelxx** [comment]
Reviving! We have a couple maintainers now... Personally I think rendering `"null"` is totally incorrect. Would appreciate a pull request adding this to the spec.
