### ISSUE TITLE
License

### ISSUE THREAD

**Issue by davidbz** [mustache/spec#102]
Can you please add a license this this project?
Thanks

**Comment by boazsegev** [comment]
I second the request.

I want to copy the testing code to my facil.io and iodine projects, in order to automate Mustache compliance... however, I wouldn't want to step on any toes (my projects are MIT licensed).

**Comment by Danappelxx** [comment]
Reviving since this is actually quite important. @pvande, can you 'sign off' on licensing this project under MIT?

**Comment by pvande** [comment]
I don't have any objections to that.

**Comment by Danappelxx** [comment]
Wonderful! Added the license 989a21a

**Comment by clach04** [comment]
Cross reference https://github.com/mustache/spec/issues/44
