### ISSUE TITLE
How do mustache avoid xss attack?

### ISSUE THREAD

**Issue by PEIYANGXINQU** [mustache/spec#105]
At first ,I use doT.js,It seems that doT do not check the input content.If the content is alert(999)</script>,then it will execute and alert the window. Now I change to use mustache.js.It seems OK.How do mustache avoid xss attack?

**Comment by Danappelxx** [comment]
It is generally up to the user of Mustache to avoid XSS, but most string interpolation is [HTML-escaped](https://github.com/mustache/spec/blob/master/specs/interpolation.yml#L44-L58).
