### ISSUE TITLE
Mustache-ES6 question or proposal

### ISSUE THREAD

**Issue by ppKrauss** [mustache/spec#108]
Mustache is an important template system for Web and non-Web applications... And Javascript   was a great inspiration and reference, for JSON and Mustache. Javascript evolved, particularly  with the ECMA's v6 edition, "ES6". Currently, the **`${x}`** of the [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) is a [*de facto* standard](https://en.wikipedia.org/wiki/De_facto_standard) for placeholder-variables.

The adoption of `{{x}}` was a good choice (resembles the  Mediawiki templates, popular in 2009), and there is no problem with it... But it was arbitrary, before 2015 there was no  Javascript-reference &mdash; that's an important part of the "standards ecosystem".  Now, maybe, we can try to restart with non-arbitrary choice.

**Question and suggestion**: is it possible (or "are there people in this community?") to create a fork **by Mustache iniciative** (suggested name "Mustache-ES6") to test and evolve to the new standard?

-----

PS: about particular Javascript implementation and optimizations, see  this [es6-template-engine](https://github.com/dondido/express-es6-template-engine) project.

**Comment by Danappelxx** [comment]
Hi! Feel free to reopen, but given this isn't an actual issue with the Mustache spec (as far as I can tell) and it hasn't sparked interest, I'm closing this issue for now.

**Comment by jgonggrijp** [comment]
The `${x}` syntax is very specific to JavaScript. I wouldn't be in favor of introducing such notation in a template language that is meant to be very portable between programming languages.

(So I agree with keeping this closed.)
