### ISSUE TITLE
HelperIn this way, the test seems like you are purely testing for the absence of functionality. I think it is more motivating if you contrast it with the desired behavior:

### ISSUE THREAD

**Issue by Dirtyyt66** [mustache/spec#184]
In this way, the test seems like you are purely testing for the absence of functionality. I think it is more motivating if you contrast it with the desired behavior:

```suggestion
    data:
      a.b: c
      a: { b: d }
    template: '{{a.b}}'
    expected: 'd'
```

This is also why I suggested "No Masking" for the test name.

_Originally posted by @jgonggrijp in https://github.com/mustache/spec/pull/180#discussion_r1402457013_

**Comment by jgonggrijp** [comment]
@Dirtyyt66 did you actually intend to report an issue or is this entirely accidental input? In the first case, please edit and I will reopen.
