### ISSUE TITLE
Should sections with lambdas /higher order functions be able to render content?

### ISSUE THREAD

**Issue by marcinkoziej** [mustache/spec#19]
Hello.

In the spec the ability to render section content in lambda is not mentioned.
Im talking about this example from http://mustache.github.com/mustache.5.html

``` javascript
{
    "name": "Willy",
    "wrapped": function() {
        return function(text) {
            return "<b>" + render(text) + "</b>"
        }
    }
}
```

this functionality is also mentioned in this post about using lambdas to implement caching or syntax highlighting: http://ozmm.org/posts/higher_order_mustache.html

If musteche doesn't accept this behaviour, what is the use of lambdas except for prepending/appending text to it's argument?

**Comment by jgonggrijp** [comment]
This discussion continues in #155.
