### ISSUE TITLE
i18n with mustache [like: {{_i}}..{{/i}}]?

### ISSUE THREAD

**Issue by marcinkoziej** [mustache/spec#24]
Hello.
What's the preferred strategy to i18nalize a mustache template?

Twitter's fork of [Mustache.js](https://github.com/bcherry/mustache.js) uses {{_i}} {{/i}} sections to callout to gettext.

Will this be ported to main mustache spec? Or should One just provide a lambda and use it like {{#i}}Some text{{/i}} ?

**Comment by jgonggrijp** [comment]
Closing this as the question seems to have been answered.
