### ISSUE TITLE
Neither mustache(1) nor mustache(5) mention implicit iterators or dotted names

### ISSUE THREAD

**Issue by mahonnaise** [mustache/spec#27]
Made me think that Mustache doesn't support these things. That's pretty bad.

http://mustache.github.com/mustache.1.html

http://mustache.github.com/mustache.5.html

On a side note, both documents still refer to mustache(7), which doesn't exist.

**Comment by jgonggrijp** [comment]
There is nowadays an updated version of the manpages hosted over here:

https://jgonggrijp.gitlab.io/wontache/mustache.5.html

Contributions can be sent to https://github.com/jgonggrijp/mustache. The file that needs editing is `man/mustache.5.ron`.

**Comment by jgonggrijp** [comment]
The official website has been updated and I now have the means to ensure it stays updated in the future.
