### ISSUE TITLE
Change Delimiters

### ISSUE THREAD

**Issue by thegrandpoobah** [mustache/spec#29]
The spec says:

```
The tag's content MUST be any two non-whitespace sequences (separated by
whitespace) EXCEPT an equals sign ('=') followed by the current closing delimiter.
```

Yet the examples include things like:

   {{= | | =}}

which to me seems to break the "non-whitespace sequence" rule. That is, the new tag delimiter should always immediatelly fllow the `=` character (or immediately precede it).

Am I misreading the little paragraph at the top?

**Comment by jgonggrijp** [comment]
Closing this as the question seems to have been addressed adequately. Please feel welcome to comment anyway.
