### ISSUE TITLE
formating of dates, numbers and more 

### ISSUE THREAD

**Issue by phloe** [mustache/spec#41]
I've been discussing the viability of mustache as a templating solution with a colleague and he raised some questions about a lacking key feature; formating. And I tend to agree with him - having this as part of the mustache spec would be very helpful.

The string representation of a date or time, the numbers of decimals of a price or the number of characters shown shouldn't be part of your viewmodel - it should (in a perfect world) be handled by the templating language.

I'm thinking something along the lines of being able to define a "format" in some form immediately after the variable name:

```
{
    price: 2.7532
}

{{price:0.00}}USD

2.75USD
```

I know JSON doesn't support a native date representation - maybe just treat an ISO datestring as a date object and present it through a format like [php's date function](http://php.net/manual/en/function.date.php) (other formats might be more fitting/standard)?

I'm sorry if this issue has been raised a thousand times (it seems so obvious somehow) - but I haven't been able to find an answer to this yet ;D

**Comment by oliverjanik** [comment]
What's the latest news?
