### ISSUE TITLE
Proposel: dynamic partials

### ISSUE THREAD

**Issue by drekka** [mustache/spec#49]
Hi all, I'm new to moustache so please correct if there is a way to do this. I've been using Mu2 and Node.js as a bit of context.

I could like to be able to create a skeleton moustache template and then tell it which partials to include. The reason for this is that using this top down approach to assembling a document means that each template only needs to be aware of the content it contains, not that which is around it. An example is this - with some help from the Mu2 developer I current need templates like this:

view

```
{
    heading: "MY content heading",
    content: "<p>Some text</p>"
}
```

Main render: content.mustache

```
{{> header}} 
{{heading}}
{{& content}}   
{{> footer}} 
```

Partial: header.moustache

```
<html>
    <headers><!-- other partials here --></headers>
    <body>
        <!-- menu bar partials, etc -->
```

Partial: footer.moustache

```
    </body>
</html>
```

This will work for the moment, but it's rather ugly because the content has to know what goes around it. It also has problems if I need (for example) to select different partials in the headers and the content. What I would much prefer to be able to do is this:

view

```
{
    contentPartial: "content",
    heading: "MY content heading",
    content: "<p>Some text</p>"
}
```

Main render: page.moustache

```
<html>
    <headers><!-- other partials here --></headers>
    <body>
        <!-- menu bar partials, etc -->
        {{> contentPartial}}
    </body>
</html>
```

Partial: content.mustache 

```
{{heading}}
{{& content}}   
```

So when the rendering encounters the `{{> contentPartial}}` code, it detects that contentPartial is a value in the view, insert's it's value and then continues to include, thus including the content.moustache partial.

Please let me know if there is a way around this issue - lamda's perhaps?

**Comment by jgonggrijp** [comment]
Superseded by #54 and #134.
