### ISSUE TITLE
When, Oh When, Mustache 2.0?

### ISSUE THREAD

**Issue by trans** [mustache/spec#53]
Is there any hope Mustache 2.0 will make a break for it within the year?

If there is a hold up b/c of so many feature possibilities and undecided choices to make about them, may I suggest that this process be divided into 2.0 and a 3.0 tracks?

For 2.0 just adopt the things you are sure about and/or already have precedence in the field. For instance Hogan.js has already adopted template inheritance. I recommend taking that, adjusting it so the notation is more intuitive/useful (for instance, [my recommendation](https://github.com/mustache/spec/issues/49#issuecomment-6652497)), and go with it. Another possibility is Handlebar.js style helpers. And personally I'd like to see Liquid style filters. But I digress. The point is pick the things that are ready or near ready to go, and make 2.0 out of those and save anything that is still well up in the air for 3.0.

Personally I feel there is some urgency to get the move on, as new template engines are making the scene to draw people away from a common standard, which Mustache has succeeded in doing more than any other for logicless templates.

**Comment by jgonggrijp** [comment]
I'm closing this, partly because the discussion is long dead but mostly because having any particular version released should not be a goal in itself.
