### ISSUE TITLE
if/else/each keywords

### ISSUE THREAD

**Issue by devinrhode2** [mustache/spec#55]
A form of the `if` keyword is being requested here: https://github.com/mustache/spec/pull/22
And similarly a form of the `each` keyword here: https://github.com/mustache/spec/pull/23
@janl made a request for an easier `else` too: http://writing.jan.io/mustache-2.0.html

I think obscuring the meaning of something that actually means `each` down to a one symbol: `,` is stupid and not the hard to read and learn.

@wesen, is there any reason you want short symbols instead of real keywords?

This should be part of Mustache 2.0.

Handlebars also has `with` and `unless` keywords, which we could consider.

**Comment by urzds** [comment]
I also would like to see an explicit "if" syntax, like @wesen mentioned in https://github.com/mustache/spec/issues/55#issuecomment-9936333.

I would enhance the syntax like so:
```mustache
{{?products}}
Product names:
{{#products}}{{name}}{{/products}}
{{^products}}
No products.
{{/products}}
```

**Comment by rekhapriyan** [comment]
Hi I have the below mustache script for my slack notification message.
- Total hits: {{#ctx.results}}{{#hits}}{{total}}{{/hits}}{{/ctx.results}}
- Period start: {{ctx.periodStart}}
- Period end: {{ctx.periodEnd}}
- Error Details:
  {{#ctx.results}}
      {{#hits}}
          {{#hits}}
              {{#_source}} 
               StoreId: {{StoreId}} 
               Env: {{Env}} 
               App: {{App}} : 
               LogType: {{LogType}}
               LogTime: {{LogTime}} 
               LogDetails: {{LogDetails}}
               {{/_source}}
          {{/hits}}
      {{/hits}}
  {{/ctx.results}}

In this alerts are generating for same error for the same Store ID. I am trying to give some condition to filter only one store id with the same error. 

Error Output now
- Error Details:
               StoreId: 32294 
               Env: prod 
               App: V2HH : 
               LogType: PRINTING_ERROR
               LogTime: 2020-01-28T21:09:25 
               LogDetails:  Printing Label is failed 2 time and error: Error: Error Domain&#x3D;UIPrintErrorDomain Code&#x3D;4 &quot;(null)&quot;
               StoreId: 32294 
               Env: prod 
               App: V2HH : 
               LogType: PRINTING_ERROR
               LogTime: 2020-01-28T21:08:52 
               LogDetails:  Printing Label is failed 2 time and error: Error: Error Domain&#x3D;UIPrintErrorDomain Code&#x3D;4 &quot;(null)&quot;
               StoreId: 32294 
               Env: prod 
               App: V2HH : 
               LogType: PRINTING_ERROR
               LogTime: 2020-01-28T21:08:33 
               LogDetails:  Printing Label is failed 2 time and error: Error: Error Domain&#x3D;UIPrintErrorDomain Code&#x3D;4 &quot;(null)&quot;
  
Need to display only one error out of these three error. Any suggestions on the mustache script to be modified to?
