### ISSUE TITLE
Partials fallback to lookup by filename

### ISSUE THREAD

**Issue by devinrhode2** [mustache/spec#56]
I wish we could have this cemented in the spec, specifically:

<b>When the lookup of a partial named 'sidebar.mustache' fails, lookup would fallback to the file named 'sidebar.mustache'.</b> If rendering is being done on the client, then this simply doesn't occur.

Of course we need to support full file paths like`../../layout.mustache`but I think this is trivial for most languages. In PHP the path string is simply placed into a file_get_contents call. However, I'd like to hear the opinions of some implementors on this. When partials reference more partials, there's potential to mixup paths, for example:

_/partials/one.mustache:_

```
Here's one.mustache
```

_/partials/two.mustache:_

```
Here's two.mustache
{{> one.mustache}}
```

_/final.mustache:_

```
Here's final.mustache
{{> partials/two.mustache}}
```

Since references would be relative, implementations need to take care to look for the file relative to the file including it.

**Comment by jgonggrijp** [comment]
Closing as this does not seem to be a spec issue.
