### ISSUE TITLE
JSON creation

### ISSUE THREAD

**Issue by davisp** [mustache/spec#7]
I just sent a pull request about a Python test, I noticed that when I generated JSON that it changed every file because the order of attribute access had changed. I elected to not include those updates in the diff. Is there a way to make the JSON generation in the Rakefile emit sorted keys?

I'm not so hip to the Ruby and wasn't able to figure anything out from the json gem docs.

**Comment by jgonggrijp** [comment]
JSON generation appears to be well-behaved nowadays.
