### ISSUE TITLE
Proposal: Mutable context objects

### ISSUE THREAD

**Issue by samwyse** [mustache/spec#72]
I've just waded through [issue 38: Template inheritance](https://github.com/mustache/spec/issues/38).  I know I'm a couple of years late to that dance, but I suspect that one reason why the proposal hasn't been adopted is that there was never any consensus on what should be done; there were at least two implementations that behaved slightly differently.  So rather than adding to an already lengthy thread, I'm going to propose something different that accomplished the same goal: Mutable context objects (MCO).  (And I think that this will also satisfy the goals of [issue 63: Inline partials](https://github.com/mustache/spec/issues/63).

MCOs use two "new-ish" bits of syntax.

```
{{<}} {{! pushes an MCO onto the context stack }}
{{$key}}value{{/key}} {{! adds a new key-value pair to it }}
{{/}} {{! pops the MCO off of the context stack}}
```

While the mutable context object is on the stack, the rest of Mustache works the same as always.

```
{{<}}
{{$hero}}Mahatma Gandhi{{/hero}}
{{hero}} is someone I admire.
{{/}}
```

The preceding renders as:

```
Mahatma Gandhi is someone I admire.
```

Note that using the same key overwrites the previous value.

```
{{<}}
{{$hero}}Mother Teresa{{/hero}}
{{hero}} is someone I admire.
{{$hero}}Harriet Tubman{{/hero}}
{{hero}} is someone I admire.
{{/}}
```

The preceding renders as:

```
Mother Teresa is someone I admire.
Harriet Tubman is someone I admire.
```

Note how this interacts with partials.  Here is an example of a partial:

```
{{! an example template }}
<html><head><title>{{title}}{{^title}}Default title{{/title}}</title></head>
<body>
{{heading}}
Hello, world!
{{footing}}
</body></html>
```

Now, let's see what happens when it is used like this:

```
{{<}}
{{$title}}Custom title{{/title}}
{{$footing}}That's all, folks!{{/footing}}
{{> template }}
{{/}}
```

You wind up with this:

```
<html><head><title>Custom title</title></head>
<body>
Hello, world!
That's all, folks!
</body></html>
```

Needless to say, you can push multiple MCOs onto the context stack; any new values are written to the most recently created MCO (and obviously disappear when it gets popped).  Any objects added to the context stack after the MCO are considered immutable, and are skipped over when adding a value.  Also, by the judicious use of {{#key}} and {{^key}} sections, you have complete control over how substitutions are performed.

BTW, I expect that the last example is going to be a common use case, so I'd suggest that the following should be interpreted as doing the same thing:

```
{{< template }}
{{$title}}Custom title{{/title}}
{{$footing}}That's all, folks!{{/footing}}
{{/ template }}
```

Finally, I know that all of this can be done via lambdas.  I would note that (a) just because _anything_ can be computed via a Turing machine doesn't mean that you should ignore other ways of doing it, and (b) lambdas are an optional part of the spec, so IMHO that isn't a good reason to reject this or any other proposal.  Also, I'm fully aware that I'm re-using sigils that other implementations have used for years.  Feel free to suggest others that I could use instead, but note that this spec could, like lambdas, be an optional part of the overall spec.  Conflicting implementations could then ignore it, possibly later adding an option to their engine to toggle the interpretation.

Your thoughts?

**Comment by jgonggrijp** [comment]
Closing this, as the proposal was superseded by template inheritance actually making it into the spec (#125) and because the comments seem to have been going in a less than constructive direction.

If someone would like to give the idea of mutable context objects another chance, please feel welcome to create a new [discussion](https://github.com/mustache/spec/discussions/categories/ideas) for it.
