### ISSUE TITLE
Missing test: triple mustache support for implicite iterator

### ISSUE THREAD

**Issue by kanru** [mustache/spec#82]
Found by a user of cl-mustache: https://github.com/kanru/cl-mustache/issues/18

The spec test doesn't have tests for `{{.}}` and `{{{.}}}` with HTML escaping characters.

**Comment by Danappelxx** [comment]
Feel free to submit a pull request - will be merged by new maintainers.

**Comment by jgonggrijp** [comment]
This one can be closed, as it was resolved in the PR referenced above.

**Comment by kanru** [comment]
Thanks!

**Comment by jgonggrijp** [comment]
Welcome!
